//go:build linux

package bpf

// DenyBytes returns the embedded BPF ELF object for the deny program.
// This is a platform-appropriate accessor for the bpf2go-generated bytes.
func DenyBytes() []byte {
	return _DenyBytes
}
