name: Bug Report
description: Report a bug in Crust
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: input
    id: version
    attributes:
      label: Crust Version
      description: Output of `crust version`
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
        - FreeBSD
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of Crust is affected?
      options:
        - Rules Engine (Layer 0/1)
        - CLI / TUI
        - Proxy
        - Configuration
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of the bug
      placeholder: What happened? What did you expect?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior
      placeholder: |
        1. Run `crust start --auto`
        2. Send a request through the proxy
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant output from `crust logs` (optional)
      render: shell
