name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of Crust does this relate to?
      options:
        - Rules Engine (Layer 0/1)
        - Sandbox (Layer 2)
        - CLI / TUI
        - Proxy
        - Configuration
        - New Area
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve? Why is it needed?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work? Include examples if possible.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you've considered (optional)
